CREATE TABLE CARRO_COMPRAS
(
	ID_CARRO             VARCHAR(20) NOT NULL,
	ID_PRESONA           VARCHAR(20) NOT NULL
);



ALTER TABLE CARRO_COMPRAS
ADD PRIMARY KEY (ID_CARRO);



CREATE TABLE CARRO_PRODUCTO
(
	IDCARRO_PRODUCTO     VARCHAR(20) NOT NULL,
	CANTIDAD             INTEGER NULL,
	ESTADO               VARCHAR(20) NULL,
	ID_CARRO             VARCHAR(20) NULL,
	ID_FACATURA          VARCHAR(20) NULL,
	ID_PRODUCTO          VARCHAR(20) NULL
);



ALTER TABLE CARRO_PRODUCTO
ADD PRIMARY KEY (IDCARRO_PRODUCTO);



CREATE TABLE CATEGORIA
(
	ID_CATEGORIA         VARCHAR(20) NOT NULL,
	TIPO                 VARCHAR(20) NULL,
	GENERO               VARCHAR(20) NULL
);



ALTER TABLE CATEGORIA
ADD PRIMARY KEY (ID_CATEGORIA);



CREATE TABLE COMENTARIO
(
	ID_COMENTARIO        VARCHAR(20) NOT NULL,
	FECHA                DATE NULL,
	COMENTARIO           VARCHAR(20) NULL,
	POSICION             INTEGER NULL,
	ID_PRODUCTO          VARCHAR(20) NOT NULL,
	ID_PRESONA           VARCHAR(20) NULL
);



ALTER TABLE COMENTARIO
ADD PRIMARY KEY (ID_COMENTARIO);



CREATE TABLE FACTURA
(
	ID_FACATURA          VARCHAR(20) NOT NULL,
	FECHA                DATE NULL,
	TOTAL                INTEGER NULL,
	CIUDAD               VARCHAR(20) NULL,
	DIRECCION            VARCHAR(20) NULL,
	ENVIO                INTEGER NULL,
	DESCUENTO            INTEGER NULL,
	IMPUESTO             INTEGER NULL,
	ID_PRESONA           VARCHAR(20) NOT NULL
);



ALTER TABLE FACTURA
ADD PRIMARY KEY (ID_FACATURA);



CREATE TABLE IMAGENES
(
	ID_IMAGEN            VARCHAR(20) NOT NULL,
	NOMBRE               VARCHAR(20) NULL,
	ID_PRODUCTO          VARCHAR(20) NULL
);



ALTER TABLE IMAGENES
ADD PRIMARY KEY (ID_IMAGEN);



CREATE TABLE PERSONA
(
	NOMBRE               VARCHAR(20) NULL,
	CORREO               VARCHAR(20) NULL,
	CLAVE                VARCHAR(20) NULL,
	ID_PRESONA           VARCHAR(20) NOT NULL,
	ID_ROL               CHAR(18) NOT NULL
);



ALTER TABLE PERSONA
ADD PRIMARY KEY (ID_PRESONA);



CREATE TABLE PRODUCTO
(
	ID_PRODUCTO          VARCHAR(20) NOT NULL,
	NOMBRE               VARCHAR(20) NULL,
	PRECIO               INTEGER NULL,
	DESCRIPCION          VARCHAR(20) NULL,
	IMAGEN               VARCHAR(20) NULL,
	ESTADO               BOOLEAN NULL,
	CREACION             DATE NULL,
	ID_CATEGORIA         VARCHAR(20) NULL
);



ALTER TABLE PRODUCTO
ADD PRIMARY KEY (ID_PRODUCTO);



CREATE TABLE ROL
(
	ID_ROL               CHAR(18) NOT NULL,
	ROL                  VARCHAR(20) NULL
);



ALTER TABLE ROL
ADD PRIMARY KEY (ID_ROL);



ALTER TABLE CARRO_COMPRAS
ADD CONSTRAINT R_10 FOREIGN KEY (ID_PRESONA) REFERENCES PERSONA (ID_PRESONA);



ALTER TABLE CARRO_PRODUCTO
ADD CONSTRAINT  R_11 FOREIGN KEY  (ID_CARRO) REFERENCES CARRO_COMPRAS (ID_CARRO);



ALTER TABLE CARRO_PRODUCTO
ADD CONSTRAINT R_12 FOREIGN KEY  (ID_FACATURA) REFERENCES FACTURA (ID_FACATURA);



ALTER TABLE CARRO_PRODUCTO
ADD CONSTRAINT  R_13 FOREIGN KEY  (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);



ALTER TABLE COMENTARIO
ADD CONSTRAINT  R_6 FOREIGN KEY  (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);



ALTER TABLE COMENTARIO
ADD CONSTRAINT R_7 FOREIGN KEY  (ID_PRESONA) REFERENCES PERSONA (ID_PRESONA);



ALTER TABLE FACTURA
ADD CONSTRAINT R_2 FOREIGN KEY (ID_PRESONA) REFERENCES PERSONA (ID_PRESONA);



ALTER TABLE IMAGENES
ADD CONSTRAINT R_8 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);



ALTER TABLE PERSONA
ADD CONSTRAINT R_1 FOREIGN KEY  (ID_ROL) REFERENCES ROL (ID_ROL);



ALTER TABLE PRODUCTO
ADD CONSTRAINT R_15 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);
